version: '3'

services:
  frontend:
    hostname: frontend
    env_file:
      - ./.env
    build:
    #  context: ./advertisements
      dockerfile: Dockerfile
    ports:
      - '443:443'

    volumes:
      - ./data:/app/data
      - ./advertisements/media:/app/advertisements/media
      - ./advertisements/static/files:/app/static/files

    restart: always
