version: '3'

services:
  frontend:
    hostname: frontend
    env_file:
      - ./.env
    build:
    #  context: ./advertisements
      dockerfile: Dockerfile
    ports:
      - '80:80'
    #volumes:
    #  - ./advertisements:/app

    volumes:
      - ./data:/app/data

    restart: always
