[tool.poetry]
name = "django"
version = "0.1.0"
description = ""
authors = ["Sergey Lebedev <ob430y@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
